image: "node:latest"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - ver
  - init
  - tests

ver-job: 
  stage: ver
  script:
    - "yarn --version"

client-init-job: 
  stage: init
  script:
    - "cd client/"
    - "yarn cache clean"
    - "rm -rf node-modules"
    - "yarn install"

server-init-job:
  stage: init
  script:
    - "cd server/"
    - "yarn cache clean"
    - "rm -rf node-modules"
    - "yarn install"

client_run_tests: 
  stage: tests
  script: 
    - "cd client/"
    - "yarn test"

server_run_tests: 
  stage: tests
  script: 
    - "cd server/"
    - "yarn test"