image: "node:5.6.0"

stages:
  - ver
  - init
  - tests

ver-job: 
  stage: ver
  script:
    - "npm --version"

client-init-job: 
  stage: init
  script:
    - "cd client/"
    - "npm cache clean"
    - "rm -rf node-modules"
    - "npm install"

server-init-job:
  stage: init
  script:
    - "cd server/"
    - "npm cache clean"
    - "rm -rf node-modules"
    - "npm install"

client_run_tests: 
  stage: tests
  script: 
    - "cd client/"
    - "npm test"

server_run_tests: 
  stage: tests
  script: 
    - "cd server/"
    - "npm test"