image: "node:latest"

stages:
  - ver
  - init
  - tests

ver-job: 
  stage: ver
  script:
    - "yarn --version"

client-init-job: 
  cache:
    key: client
    paths:
      - "node_modules"
  stage: init
  script:
    - "cd client/"
    - "yarn cache clean"
    - "rm -rf node-modules"
    - "yarn install"

server-init-job:
  cache:
    key: server
    paths:
      - "node_modules"
  stage: init
  script:
    - "cd server/"
    - "yarn cache clean"
    - "rm -rf node-modules"
    - "yarn install"

client_run_tests: 
  cache:
    key: client
    paths:
      - "/node_modules"
    policy: pull
  stage: tests
  script: 
    - "cd client/"
    - "yarn test"

server_run_tests: 
  cache:
    key: server
    paths:
      - "/node_modules"
    policy: pull
  stage: tests
  script: 
    - "cd server/"
    - "yarn test"