export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_GENRE = 'UPDATE_GENRE';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const FETCH_MOVIES_BEGIN   = 'FETCH_MOVIES_BEGIN';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';